services:
  api:
    build: ./server
    container_name: clicker_api
    env_file: .env         
    ports:
      - "8080:8080"
    depends_on:
      - redis
    restart: unless-stopped

  web:
    build: ./webapp
    container_name: clicker_web
    environment:
      - NODE_ENV=production
      - PORT=3000         
      - NEXT_TELEMETRY_DISABLED=1
    expose:
      - "3000"          

  nginx:
    image: nginx:1.27-alpine
    container_name: clicker_nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "3000:80"          
    depends_on:
      - api
      - web
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: clicker_redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "60", "1000", "--appendonly", "yes"]
    restart: unless-stopped
